datadir: /mnt/netdisk1/stephan/WeatherBench
name: u_component_of_wind
era_var_name: u_component_of_wind
level_type: pressure
pressure_level:
  - 50
  - 100
  - 150
  - 200
  - 250
  - 300
  - 400
  - 500
  - 600
  - 700
  - 850
  - 925
  - 1000
res:
  - 1.40625
  - 2.8125
  - 5.625
