datadir: /media/rasp/Elements/weather-benchmark
name: potential_vorticity
era_var_name: potential_vorticity
level_type: pressure
pressure_level:
  - 50
  - 100
  - 150
  - 200
  - 250
  - 300
  - 400
  - 500
  - 600
  - 700
  - 850
  - 925
  - 1000
res:
  - 1.40625
  - 2.8125
  - 5.625
